[workspace]
members = ["sitelen-core", "sitelen-cli", "sitelen-wasm"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
authors = ["Olaf T.A. Janssen <olaf.janssen@pm.me>"]
license = "MIT"
repository = "https://github.com/olafjanssen/sitelen-sitelen-renderer"
